name: Build Kernel with SukiSU-Ultra and AnyKernel3
on:
  push:
    branches:
      - walt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc git zip binutils-aarch64-linux-gnu gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf

      - name: Setup toolchain
        run: |
          wget https://github.com/kdrag0n/proton-clang/releases/download/13.0.0/proton-clang-13.0.0.tar.gz
          tar -xzf proton-clang-13.0.0.tar.gz
          export PATH=$(pwd)/proton-clang/bin:$PATH
          clang --version

      - name: Check for integrate_sukisu.sh
        run: |
          ls -la
          if [ ! -f integrate_sukisu.sh ]; then echo "File integrate_sukisu.sh not found"; exit 1; fi

      - name: Integrate SukiSU-Ultra
        run: |
          bash integrate_sukisu.sh

      - name: Check for munch_defconfig
        run: |
          ls -la arch/arm64/configs/
          ls -la arch/arm64/configs/vendor/
          if [ ! -f arch/arm64/configs/vendor/munch_defconfig ]; then echo "File munch_defconfig not found in vendor"; exit 1; fi

      - name: Copy munch_defconfig
        run: |
          cp arch/arm64/configs/vendor/munch_defconfig arch/arm64/configs/

      - name: Build kernel
        env:
          CROSS_COMPILE_ARM32: arm-linux-gnueabihf-
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux-gnu- CC=clang munch_defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CLANG_TRIPLE=aarch64-linux
